services:
  delivery-management-service:
    build: ./delivery-management-service
    container_name: delivery-management-service
    ports:
      - "8084:8084"
    environment:
      # Change the host/IP if needed. For Windows/macOS, host.docker.internal works.
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/deliverydb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  order-management-service:
    build: ./order-management-service
    container_name: order-management-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/orderdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  restaurant-management-service:
    build: ./restaurant-management-service
    container_name: restaurant-management-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/restaurantdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
