services:
  delivery-management-service:
    build:
      context: ./delivery-management-service
    image: delivery-management-service:latest
    container_name: delivery-management-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/deliverydb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  order-management-service:
    build:
      context: ./order-management-service
    image: order-management-service:latest
    container_name: order-management-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/orderdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  restaurant-management-service:
    build:
      context: ./restaurant-management-service
    image: restaurant-management-service:latest
    container_name: restaurant-management-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/restaurantdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  api-gateway:
    build:
      context: ./api-gateway
    image: api-gateway:latest
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - delivery-management-service
      - order-management-service
      - restaurant-management-service