spring:
  application:
    name: api-gateway
  cloud:
    kubernetes:
      discovery:
        enabled: true         # turn on K8s-based DiscoveryClient
    gateway:
      discovery:
        locator:
          enabled: true      # dynamically create routes for all services
      routes:
        - id: order-route
          uri: lb://order-management-service
          predicates:
            - Path=/orders/**
        - id: delivery-route
          uri: lb://delivery-management-service
          predicates:
            - Path=/deliveries/**
        - id: restaurant-route
          uri: lb://restaurant-management-service
          predicates:
            - Path=/restaurants/**
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
