server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    config:
      enabled: false

    gateway:
      routes:
        - id: order-service
          uri: http://order-management-service:8083   # ← Kubernetes Service name
          predicates:
            - Path=/api/orders/**
        - id: restaurant-service
          uri: http://restaurant-management-service:8082
          predicates:
            - Path=/api/restaurants/**
        - id: delivery-service
          uri: http://delivery-management-service:8084
          predicates:
            - Path=/api/deliveries/**
        - id: admin-service
          uri: http://restaurant-management-service:8082   # or your admin service name
          predicates:
            - Path=/api/admin/**
        - id: drivers-service
          uri: http://delivery-management-service:8084     # or your drivers service name
          predicates:
            - Path=/api/drivers/**
