server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    config:
      enabled: false

    gateway:
      routes:
        - id: order-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/orders/**
        - id: restaurant-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/restaurants/**
        - id: delivery-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/deliveries/**
        - id: admin-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/admin/**
        - id: drivers-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/drivers/**
